service: mylg-v2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    ALLOWED_ORIGINS: https://beta.mylg.studio,https://mylg.studio,http://localhost:3000
  httpApi:
    cors: false  # handled in Lambda for dynamic origins
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource: "arn:aws:execute-api:*:*:*"

functions:
  userRouter:
    handler: auth/index.handler
    layers:
      - { Ref: SharedUtilsLayerLambdaLayer } # defined below
    events:
      - httpApi:
          method: ANY
          path: /auth/{proxy+}

  projectsRouter:
    handler: projects/index.handler
    layers:
      - { Ref: SharedUtilsLayerLambdaLayer }
    events:
      - httpApi:
          method: ANY
          path: /projects/{proxy+}

  messagesRouter:
    handler: messages/index.handler
    layers:
      - { Ref: SharedUtilsLayerLambdaLayer }
    events:
      - httpApi:
          method: ANY
          path: /messages/{proxy+}

  wsProvider:
    handler: ws/index.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
      - websocket:
          route: sendMessage

layers:
  sharedUtilsLayer:
    path: shared-layer   # contains nodejs/utils/cors.mjs etc.
    name: shared-utils
    compatibleRuntimes: [nodejs18.x]
