service: mylg-v2-websocket
frameworkVersion: '3'

custom:
  env: ${file(../serverless.common.yml):env}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 15
  environment:
    WEBSOCKET_ENDPOINT: ${env:WEBSOCKET_ENDPOINT}

    ${self:custom.env}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchWriteItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:CONNECTIONS_TABLE}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:CONNECTIONS_TABLE}/index/*
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource: "arn:aws:execute-api:${aws:region}:${aws:accountId}:*/${sls:stage}/POST/@connections/*"

functions:
  onConnect:
    handler: websocket/onConnect.handler
    events:
      - websocket:
          route: $connect
  onDisconnect:
    handler: websocket/onDisconnect.handler
    events:
      - websocket:
          route: $disconnect
  onDefault:
    handler: websocket/default.handler
    events:
      - websocket:
          route: $default
  sendMessage:        # optional custom route used by your default code paths
    handler: websocket/default.handler
    events:
      - websocket:
          route: sendMessage

package:
  patterns:
    - websocket/**
    - '!**/*.map'
