AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MYLG DynamoDB schema with explicit table names

Resources:

  # ---------- Users ----------
  UserProfiles:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: UserProfiles
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  # ---------- Invitations ----------
  ProjectInvitations:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: ProjectInvitations
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: inviteId
          AttributeType: S
        - AttributeName: senderId
          AttributeType: S
        - AttributeName: recipientId
          AttributeType: S
      KeySchema:
        - AttributeName: inviteId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: senderId-index
          KeySchema:
            - AttributeName: senderId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: recipientId-index
          KeySchema:
            - AttributeName: recipientId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # ---------- Inbox (single table) ----------
  Inbox:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Inbox
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: conversationId
          AttributeType: S
        - AttributeName: threadId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: conversationId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: threadId-index
          KeySchema:
            - AttributeName: threadId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # ---------- Messages ----------
  Messages:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Messages
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: conversationId
          AttributeType: S
        - AttributeName: messageId
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: conversationId
          KeyType: HASH
        - AttributeName: messageId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: InboxIndex
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # ---------- ProjectMessages ----------
  ProjectMessages:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: ProjectMessages
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: messageId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH
        - AttributeName: messageId
          KeyType: RANGE

  # ---------- Notifications ----------
  Notifications:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Notifications
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp#uuid
          AttributeType: S
        - AttributeName: dedupeId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: timestamp#uuid
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: dedupeId-index
          KeySchema:
            - AttributeName: dedupeId
              KeyType: HASH
            - AttributeName: timestamp#uuid
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # ---------- Projects ----------
  Projects:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Projects
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH

  # ---------- Tasks ----------
  Tasks:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Tasks
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: taskId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH
        - AttributeName: taskId
          KeyType: RANGE

  # ---------- Events ----------
  Events:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Events
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: startAt
          AttributeType: S
        - AttributeName: budgetItemId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH
        - AttributeName: eventId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: budgetItemId-index
          KeySchema:
            - AttributeName: budgetItemId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # ---------- Budgets ----------
  Budgets:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Budgets
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: budgetItemId
          AttributeType: S
        - AttributeName: budgetId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH
        - AttributeName: budgetItemId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: budgetId-index
          KeySchema:
            - AttributeName: budgetId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: budgetItemId-index
          KeySchema:
            - AttributeName: budgetItemId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # ---------- Galleries ----------
  Galleries:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Galleries
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: galleryId
          AttributeType: S
        - AttributeName: projectId
          AttributeType: S
      KeySchema:
        - AttributeName: galleryId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: projectId-index
          KeySchema:
            - AttributeName: projectId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # ---------- WebSocket connections ----------
  Connections:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: Connections
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-sessionId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: sessionId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  UserProfilesTableName:
    Value: !Ref UserProfiles
  ProjectInvitationsTableName:
    Value: !Ref ProjectInvitations
  InboxTableName:
    Value: !Ref Inbox
  MessagesTableName:
    Value: !Ref Messages
  ProjectMessagesTableName:
    Value: !Ref ProjectMessages
  NotificationsTableName:
    Value: !Ref Notifications
  ProjectsTableName:
    Value: !Ref Projects
  TasksTableName:
    Value: !Ref Tasks
  EventsTableName:
    Value: !Ref Events
  BudgetsTableName:
    Value: !Ref Budgets
  GalleriesTableName:
    Value: !Ref Galleries
  ConnectionsTableName:
    Value: !Ref Connections