service: projects
frameworkVersion: '3'

custom:
  app: mylg
  ver: v12
  env: ${file(../serverless.common.yml):env}
  cors: ${file(../serverless.common.yml):cors}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 15
  stackName: ${self:custom.app}-${self:custom.ver}-${self:service}-${sls:stage}
  httpApi:
    cors: false  # dynamic CORS handled in Lambda
    name: ${self:custom.app}-${self:custom.ver}-${self:service}-api-${sls:stage}
  tags:
    App: MYLG
    Version: v1.2
    Domain: projects
    Stage: ${sls:stage}
  environment:
    # CORS (layer reads these)
    ALLOWED_ORIGINS: https://beta.mylg.studio,https://mylg.studio,http://localhost:3000
    CORS_WILDCARD_HOSTS: mylg.studio
    CORS_ALLOW_CREDENTIALS: "false"
    CORS_DEFAULT_ORIGIN: ${self:custom.cors.CORS_DEFAULT_ORIGIN}

    # Tables: pull from the shared file
    ${self:custom.env}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            # Projects core
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:PROJECTS_TABLE}

            # Tasks
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:TASKS_TABLE}

            # Events (+ optional startAt GSI)
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:EVENTS_TABLE}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:EVENTS_TABLE}/index/*

            # Budgets (+ GSIs for budgetId and budgetItemId)
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:BUDGETS_TABLE}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:BUDGETS_TABLE}/index/*

            # Galleries (+ projectId GSI)
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:GALLERIES_TABLE}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:GALLERIES_TABLE}/index/*

functions:
  projectsRouter:
    name: ${self:custom.app}-${self:custom.ver}-projects-router-${sls:stage}
    # NOTE: point this to where your file actually lives.
    # If the file is backend/projects/router.mjs at the service root, use "router.handler".
    # If it's in src/router.mjs, keep "src/router.handler".
    handler: router.handler
    layers:
      - ${cf:shared-layer-${sls:stage}.SharedUtilsLayerArn}
    events:
      - httpApi:
          path: /projects
          method: ANY
      - httpApi:
          path: /projects/{proxy+}
          method: ANY
      - httpApi:
          path: /projects/health
          method: ANY
      # include this only if you enabled the convenience routes /budgets/by*
      - httpApi:
          path: /budgets/{proxy+}
          method: ANY

package:
  patterns:
    # include the router + anything it imports (node_modules auto-included)
    - router.mjs
    - '!**/*.map'
    - '!node_modules/.bin/**'
